name: ci 
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - run: pip install "node==1.0"
      - run: pip install "mkdocs==1.3.1"
      - run: pip install "mkdocs-material==8.5.2"
      - run: node docs/pages/repertoire/converter.js | mkdocs gh-deploy --force
